# Generated by Django 5.2.5 on 2025-08-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_document_roleapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("role", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="roleapplication",
            name="document1",
        ),
        migrations.RemoveField(
            model_name="roleapplication",
            name="document2",
        ),
        migrations.RemoveField(
            model_name="roleapplication",
            name="role",
        ),
        migrations.AddField(
            model_name="roleapplication",
            name="form_data",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("checkbox", "Checkbox"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "role_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="accounts.roleform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roleapplication",
            name="role_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.roleform",
            ),
        ),
    ]
