# Generated by Django 5.2.5 on 2025-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_roleform_remove_roleapplication_document1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seller_tier",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
