# Generated by Django 5.2.5 on 2025-08-13 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_seller_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleApplicationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="role_applications/")),
                ("field_name", models.CharField(max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="accounts.roleapplication",
                    ),
                ),
            ],
        ),
    ]
