# Generated by Django 5.2.5 on 2025-08-14 10:46

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_roleapplicationfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleapplication",
            name="verification_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roleapplication",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roleapplicationfile",
            name="file",
            field=models.FileField(
                upload_to="role_applications/",
                validators=[
                    accounts.validators.validate_file_extension,
                    accounts.validators.validate_file_size,
                ],
            ),
        ),
    ]
