# Generated by Django 5.2.5 on 2025-08-14 12:46

from django.db import migrations

def create_vip_employer_role_form(apps, schema_editor):
    RoleForm = apps.get_model('accounts', 'RoleForm')
    FormField = apps.get_model('accounts', 'FormField')

    vip_employer_form, created = RoleForm.objects.get_or_create(
        name='VIP Employer Application',
        role='vip_employer'
    )

    if created:
        FormField.objects.create(
            role_form=vip_employer_form,
            label='Company Registration Documents',
            field_type='file',
            required=True
        )
        FormField.objects.create(
            role_form=vip_employer_form,
            label='Business License or Tax ID',
            field_type='file',
            required=True
        )
        FormField.objects.create(
            role_form=vip_employer_form,
            label='Logo/Branding Assets',
            field_type='image',
            required=True
        )
        FormField.objects.create(
            role_form=vip_employer_form,
            label='Selfie of Company Representative with Valid ID',
            field_type='image',
            required=True
        )
        FormField.objects.create(
            role_form=vip_employer_form,
            label='I agree to the VIP Employer Terms & Conditions',
            field_type='checkbox',
            required=True
        )

def delete_vip_employer_role_form(apps, schema_editor):
    RoleForm = apps.get_model('accounts', 'RoleForm')
    RoleForm.objects.filter(role='vip_employer').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_roleapplication_verification_details_and_more'),
    ]

    operations = [
        migrations.RunPython(create_vip_employer_role_form, delete_vip_employer_role_form),
    ]
