# Generated by Django 5.2.5 on 2025-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20250814_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_vip_employer",
            field=models.BooleanField(default=False),
        ),
    ]
