# Generated by Django 5.2.5 on 2025-08-14 19:43

from django.db import migrations

def create_standard_employer_role_form(apps, schema_editor):
    RoleForm = apps.get_model('accounts', 'RoleForm')
    RoleForm.objects.get_or_create(
        name='Standard Employer Application',
        role='standard_employer'
    )

def delete_standard_employer_role_form(apps, schema_editor):
    RoleForm = apps.get_model('accounts', 'RoleForm')
    RoleForm.objects.filter(role='standard_employer').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_vip_employer'),
    ]

    operations = [
        migrations.RunPython(create_standard_employer_role_form, delete_standard_employer_role_form),
    ]
