# Generated by Django 5.2.5 on 2025-08-14 17:11

import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_auditevent_jobapplication_applicationnote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    jobs.validators.validate_file_extension_pdf,
                    jobs.validators.validate_file_size_10mb,
                ],
            ),
        ),
    ]
