# Generated by Django 5.2.5 on 2025-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobapplication_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_days", models.PositiveIntegerField(default=1)),
                ("max_days", models.PositiveIntegerField(default=30)),
            ],
            options={
                "verbose_name_plural": "Featured Pricing",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="featured_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="tier",
            field=models.CharField(
                choices=[("standard", "Standard"), ("vip", "VIP")],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
