# Generated by Django 5.2.5 on 2025-08-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_create_default_pricing_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
